document.writeln("<link href=\"http://mrpi.cwlai.com/templets/mzx/css/headerFooter.css\" type=\"text/css\" rel=\"stylesheet\" />");
document.writeln("<style type=\"text/css\">");
document.writeln(".diseaseMenu {width:100%;height:80px;line-height:80px;background-color:#FFF;-moz-box-shadow:0 0 8px rgba(34,23,20,.5);-webkit-box-shadow:0 0 8px rgba(34,23,20,.5);box-shadow:0 0 8px rgba(34,23,20,.5);overflow:hidden;}");
document.writeln(".menuScroll1_lists {width:100%;height:80px;overflow:hidden;}");
document.writeln(".menuScroll1_lists li {float:left;height:80px;line-height:80px;padding:0 46px;}");
document.writeln(".menuScroll1_lists li a {display:block;width:100%;height:100%;font-size:30px;color:#6A5436;}");
document.writeln(".menuScroll1_lists li a span {box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;display:block;padding:0 10px;height:100%;border-bottom:6px solid #fff}");
document.writeln(".menuScroll1_lists li.active a span {border-bottom:6px solid #d70a50;}");
document.writeln("@media screen and (min-width:320px) and (max-width:900px) {");
document.writeln(".diseaseMenu {height:40px;line-height:40px;}");
document.writeln(".menuScroll1_lists {height:40px;}");
document.writeln(".menuScroll1_lists li {height:40px;line-height:40px;padding:0 23px;}");
document.writeln(".menuScroll1_lists li a {font-size:16px;}");
document.writeln(".menuScroll1_lists li a span {padding:0 5px;border-bottom:3px solid #fff}");
document.writeln(".menuScroll1_lists li.active a span {border-bottom:3px solid #d70a50}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div id=\"header\" class=\"header relative\">");
document.writeln("  <div class=\"showMenu absolute\"><a href=\"javascript:void(0)\"></a></div>");
document.writeln("  <div class=\"logo absolute\"></div>");
document.writeln("  <a href=\"tel:031166537777\" class=\"topTell absolute\"></a>");
document.writeln("  <div id=\"popMenu\" class=\"popMenu\">");
document.writeln("    <div class=\"menulists\">");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>眼部整形</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/yamzx/syp\">双眼皮</a> <a target=\"_blank\" href=\"/zxmr/yamzx/kyj\">开眼角</a> <a target=\"_blank\" href=\"/zxmr/yamzx/qyd\">祛眼袋</a> <a target=\"_blank\" href=\"/zxmr/yamzx/ypsc\">眼皮松弛</a> </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/yamzx/sjxc\">上睑下垂</a><a target=\"_blank\" href=\"/zxmr/yamzx/wc\">卧蚕</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>鼻部整形</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/bbzx/zhlb\">综合隆鼻</a> <a target=\"_blank\" href=\"/zxmr/bbzx/jtlb\">假体隆鼻</a> <a target=\"_blank\" href=\"/zxmr/bbzx/ztlb\">自体隆鼻</a> <a target=\"_blank\" href=\"/zxmr/bbzx/zslb\">注射隆鼻</a> </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/bbzx/bjzx\">鼻尖整形</a> <a target=\"_blank\" href=\"/zxmr/bbzx/btsx\">鼻头缩小</a> <a target=\"_blank\" href=\"/zxmr/bbzx/bysx\">鼻翼缩小</a> <a target=\"_blank\" href=\"/zxmr/bbzx/wbjz\">歪鼻矫正</a> </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/bbzx/ctbjz\">朝天鼻</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>胸部整形</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/xbzx/zhlx\">综合隆胸</a> <a target=\"_blank\" href=\"/zxmr/xbzx/jtlx\">假体隆胸</a> <a target=\"_blank\" href=\"/zxmr/xbzx/ztlx\">自体隆胸</a> <a target=\"_blank\" href=\"/zxmr/xbzx/frqc\">副乳切除</a> </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/xbzx/rfxc\">乳房下垂</a> <a target=\"_blank\" href=\"/zxmr/xbzx/rtnx\">乳头内陷</a> <a target=\"_blank\" href=\"/zxmr/xbzx/rtsx\">乳头缩小</a> <a target=\"_blank\" href=\"/zxmr/xbzx/rysx\">乳晕缩小</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>面部整形</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/ymzx/glx\">改脸型</a> <a target=\"_blank\" href=\"/zxmr/ymzx/lgtc\">泪沟填充</a> <a target=\"_blank\" href=\"/zxmr/ymzx/cbzx\">唇部整形</a> <a target=\"_blank\" href=\"/zxmr/ymzx/fpgj\">丰苹果肌</a> </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/ymzx/ftyx\">丰太阳穴</a> <a target=\"_blank\" href=\"/zxmr/ymzx/fet\">丰额头</a>  <a target=\"_blank\" href=\"/zxmr/ymzx/qgzx\">颧骨整形</a> <a target=\"_blank\" href=\"/zxmr/ymzx/xbzx\">下巴整形</a>  </li>");
document.writeln("          <li> <a target=\"_blank\" href=\"/zxmr/ymzx/xgjzx\">下颌角整形</a> <a target=\"_blank\" href=\"/zxmr/ymzx/fmj\">丰面颊</a></li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>吸脂瘦身</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li><a target=\"_blank\" href=\"/zxmr/xzzx/qsxz\">全身吸脂</a> <a target=\"_blank\" href=\"/zxmr/xzzx/yfxz\">腰腹吸脂</a>  <a target=\"_blank\" href=\"/zxmr/xzzx/xtxz\">小腿吸脂</a><a target=\"_blank\" href=\"/zxmr/xzzx/dtxz\">大腿吸脂</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/zxmr/xzzx/mbxz\">面部吸脂</a><a target=\"_blank\" href=\"/zxmr/xzzx/tbxz\">臀部吸脂</a><a target=\"_blank\" href=\"/zxmr/xzzx/sbxz\">手臂吸脂</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>皮肤美容</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/pfmr/czjf/eqcz\">额区除皱</a> <a target=\"_blank\" href=\"/pfmr/czjf/yzcz\">眼周除皱</a> <a target=\"_blank\" href=\"/pfmr/czjf/mbcz\">面部除皱</a> <a target=\"_blank\" href=\"/pfmr/jgqtj/qtj\">青胎记</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/pfmr/czjf/xmbcz\">下面部除皱</a><a target=\"_blank\" href=\"/pfmr/czjf/rsw\">妊娠纹</a><a target=\"_blank\" href=\"/zxmr/xzzx/sxb\">双下巴</a><a target=\"_blank\" href=\"/pfmr/qbqd/hhb\">黄褐斑</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/pfmr/qbqd/qb\">雀斑</a><a target=\"_blank\" href=\"/pfmr/qbqd/sb\">晒斑</a><a target=\"_blank\" href=\"/pfmr/qbqd/dd\">痘痘</a><a target=\"_blank\" href=\"/pfmr/qbqd/dy\">痘印</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/pfmr/nfmb/nfmb\">嫩肤美白</a><a target=\"_blank\" href=\"/pfmr/nfmb/shxs\">祛红血丝</a><a target=\"_blank\" href=\"/pfmr/nfmb/mkcd\">毛孔粗大</a><a target=\"_blank\" href=\"/pfmr/nfmb/fsah\">肤色暗黄</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/pfmr/jgqtj/ttz\">太田痣</a><a target=\"_blank\" href=\"/pfmr/yjtm/tm\">脱毛</a><a target=\"_blank\" href=\"/pfmr/jgqz/qzqy\">去痣去疣</a><a target=\"_blank\" href=\"/pfmr/jgqtj/hqsz\">褐青色痣</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/pfmr/jgqtj/htj\">红胎记</a><a target=\"_blank\" href=\"/pfmr/jgqtj/xhbz\">鲜红斑痣</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("      <div class=\"menulist\">");
document.writeln("        <h3>注射美容</h3>");
document.writeln("        <ul class=\"menuItems clearfix\">");
document.writeln("          <li> <a target=\"_blank\" href=\"/zsmr/zscz/qyww\">祛鱼尾纹</a> <a target=\"_blank\" href=\"/zsmr/zscz/mjw\">眉间纹</a> <a target=\"_blank\" href=\"/zsmr/zscz/ttw\">抬头纹</a> <a target=\"_blank\" href=\"/zsmr/zscz/flw\">法令纹</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/zsmr/zscz/zjw\">嘴角纹</a><a target=\"_blank\" href=\"/zsmr/zscz/jw\">颈纹</a><a target=\"_blank\" href=\"/zsmr/zscz/bns\">玻尿酸</a><a target=\"_blank\" href=\"/zsmr/zscz/botox\">botox</a> </li>");
document.writeln("          <li><a target=\"_blank\" href=\"/zsmr/zscz/jydb\">胶原蛋白</a><a target=\"_blank\" href=\"/zsmr/slss/zssl\">注射瘦脸</a><a target=\"_blank\" href=\"/zsmr/slss/zssxt\">注射瘦腿</a> </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\"menuBtn\"><span>展开更多</span><i></i></div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</div>");